"""
Model Performance router — GET /api/model-performance

Returns the model evaluation metrics generated by the training notebook.
These metrics come from evaluating the Enhanced U-Net on the held-out test set.

The data is loaded from a `model_metrics.json` file in the backend directory.
If the file does not exist or hasn't been populated by real training, the
endpoint returns a clear "not yet trained" response.
"""

import json
import logging
import os

from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["model-performance"])

METRICS_FILE = os.path.join(os.path.dirname(__file__), "..", "model_metrics.json")
METRICS_FILE = os.path.normpath(METRICS_FILE)


class ModelPerformanceResponse(BaseModel):
    """Model performance data from held-out test evaluation."""
    trained: bool
    model_name: str
    architecture_changed: bool
    test_samples: int
    positive_masks: int
    empty_masks: int
    dice_mean: float
    dice_std: float
    iou_mean: float
    iou_std: float
    precision: float
    recall: float
    specificity: float
    pixel_accuracy: float
    prediction_threshold: float
    training_history: Optional[dict] = None
    message: Optional[str] = None


@router.get("/model-performance", response_model=ModelPerformanceResponse)
async def get_model_performance():
    """
    Return model evaluation metrics from the held-out test set.

    These are generated by running the training notebook — NOT fabricated.
    If no training has been done, returns zeroed-out metrics with trained=false.
    """
    if os.path.isfile(METRICS_FILE):
        try:
            with open(METRICS_FILE, "r") as f:
                data = json.load(f)

            # Check if real training was done (test_samples > 0 indicates real eval)
            trained = data.get("test_samples", 0) > 0

            return ModelPerformanceResponse(
                trained=trained,
                model_name=data.get("model_name", "Enhanced U-Net"),
                architecture_changed=data.get("architecture_changed", False),
                test_samples=data.get("test_samples", 0),
                positive_masks=data.get("positive_masks", 0),
                empty_masks=data.get("empty_masks", 0),
                dice_mean=data.get("dice_mean", 0.0),
                dice_std=data.get("dice_std", 0.0),
                iou_mean=data.get("iou_mean", 0.0),
                iou_std=data.get("iou_std", 0.0),
                precision=data.get("precision", 0.0),
                recall=data.get("recall", 0.0),
                specificity=data.get("specificity", 0.0),
                pixel_accuracy=data.get("pixel_accuracy", 0.0),
                prediction_threshold=data.get("prediction_threshold", 0.5),
                training_history=data.get("training_history"),
                message="Metrics loaded from real test evaluation." if trained
                        else "Training has not been completed yet. Run the notebook to populate metrics.",
            )
        except Exception as exc:
            logger.error("Failed to read model_metrics.json: %s", exc)

    # File does not exist or failed to load
    return ModelPerformanceResponse(
        trained=False,
        model_name="Enhanced U-Net",
        architecture_changed=False,
        test_samples=0,
        positive_masks=0,
        empty_masks=0,
        dice_mean=0.0,
        dice_std=0.0,
        iou_mean=0.0,
        iou_std=0.0,
        precision=0.0,
        recall=0.0,
        specificity=0.0,
        pixel_accuracy=0.0,
        prediction_threshold=0.5,
        message="model_metrics.json not found. Run the training notebook to generate real metrics.",
    )
